# Generated by Django 5.0.1 on 2025-04-02 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tradingSim_app", "0002_stockdata"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StockData",
            new_name="StockPrice",
        ),
    ]
