# Generated by Django 5.0.1 on 2025-04-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tradingSim_app", "0003_rename_stockdata_stockprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockprice",
            name="moving_average_5min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
